spring.application.name=doctor-appointment-system
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_management
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt.secret=9a67a86c7cfc70a82b9a7f3408a0d4c9d96850a11204d6032d8471b0586e3f88f292215c0e1762c2f1f0a28f828a2a9e3a6c11b0e01cc4c478a509930f14841d
app.jwt.expiration-milliseconds=86400000
